version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: betting-mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - betting-network
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: betting-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - betting-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: betting-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/virtual_betting
      - REDIS_URL=redis://redis:6379
      - PORT=3000
      - IP_REGISTRATION_LIMIT=2
      - IP_TRACKING_DURATION=2592000000
    depends_on:
      - mongodb
      - redis
    networks:
      - betting-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: betting-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - betting-network
    restart: unless-stopped

networks:
  betting-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local